version: '3'

services:
  db_service:
    container_name: openJiraDB
    image: mongo:5
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGODB_DATABASE: open_jira_db
    volumes:
      - ./mongo:/data/db